# Problem Statement1: Write a Python program to multiply a M * N matrix by N * A matrix and create a real matrix product.

In [1]:
#pip install numpy

In [2]:
import numpy as np

#Getting the input values from user

M=int(input("Enter value M: "))
N=int(input("Enter value N: "))
A=int(input("Enter value A: "))

array_first=np.random.rand(M,N)
array_second=np.random.rand(N,A)

#performing matrix multiplication with dot function
result=np.dot(array_first,array_second)

#printing matrix and their product
print("\nFirst array:",array_first)
print("\nSecond array:",array_second)
print("\nDot product of two arrays:",result)


Enter value M: 5
Enter value N: 3
Enter value A: 2

First array: [[0.90968938 0.37583108 0.675114  ]
 [0.99721166 0.30613221 0.67992125]
 [0.47667624 0.63811663 0.06660687]
 [0.40511824 0.94649664 0.751835  ]
 [0.34391561 0.43217596 0.40395053]]

Second array: [[0.51874784 0.22871907]
 [0.00203733 0.4923748 ]
 [0.96034543 0.41000967]]

Dot product of two arrays: [[1.12100774 0.66991633]
 [1.17088435 0.65758739]
 [0.31254042 0.45052695]
 [0.93410385 0.86694898]
 [0.56721801 0.45707623]]


# Problem Statement2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

In [3]:
import numpy as np
d=list(map(str,input("Enter values:").split()))
print("\nOriginal Array:")
print(np.array(d))
a=np.char.isdigit(d)
b=np.char.islower(d)
c=np.char.isupper(d)
print("Digits only =",a)
print("Lower cases only =",b)
print("Upper cases only =",c)


Enter values:Python PHP JS Examples html5 5

Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


# Problem Statement3:Write a program thatreads two space-separated positive integers X and Y as input and perform the following tasks:

In [4]:
import numpy as np 

In [5]:
X, Y = map(int, input("Enter two space-separated positive integers X and Y: ").split())

Enter two space-separated positive integers X and Y: 7 9


Tasks to be performed:

1.Create a list (lst1) starting at one (1) with 16 elements at a step of X

In [6]:
l1=list(range(1,16*X,X))

2.Create a list (lst2) starting at one (1) with 16 elements at a step of Y

In [7]:
l2=list(range(1,16*Y,Y))

3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

In [8]:
np1=np.array(l1)
np2=np.array(l2)

4.Reshape both the NumPy arrays to (4,4)

In [9]:
np1=np1.reshape(4,4)
np2=np2.reshape(4,4)

5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)

In [10]:
np3=np1-np2

6.Print all the elements of np3 in a single dimension list like the format as shown below:a.[n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [11]:
print(np3.flatten())

[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


# Problem Statement4: Write a Python program thattakes two integer-NumPy arrays, P and Q of shape [3∗3]and performthe following task:

In [12]:
import numpy as np

P_val = np.array(list(map(int, input("Enter integers for matrix P: ").split()))).reshape(3, 3)
Q_val = np.array(list(map(int, input("Enter integers for matrix Q: ").split()))).reshape(3, 3)

P = np.array(P_val)
Q = np.array(Q_val)


Enter integers for matrix P: 23 56 87 3 6 96 4 6 78
Enter integers for matrix Q: 12 34 54 7 2 54 6 2 78


Task to be performed:

Print the element-wise difference of the matrix P and Q(P-Q)

In [13]:
result = P - Q

In [14]:
#print("Element-wise difference of matrix P and Q:")
print(result)

[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
